import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("transaction_entries").del();

    // Inserts seed entries
    await knex("transaction_entries").insert([
        { id: 1, transaction_type_id: 1, coa_id: 1, is_credit: 0 },
        { id: 2, transaction_type_id: 1, coa_id: 2, is_credit: 1 },
        { id: 3, transaction_type_id: 2, coa_id: 1, is_credit: 1 },
        { id: 4, transaction_type_id: 2, coa_id: 2, is_credit: 0 },
        { id: 5, transaction_type_id: 3, coa_id: 1, is_credit: 0 },
        { id: 6, transaction_type_id: 3, coa_id: 3, is_credit: 1 },
        { id: 7, transaction_type_id: 4, coa_id: 1, is_credit: 1 },
        { id: 8, transaction_type_id: 4, coa_id: 3, is_credit: 0 },
        { id: 9, transaction_type_id: 5, coa_id: 1, is_credit: 1 },
        { id: 10, transaction_type_id: 5, coa_id: 14, is_credit: 0 },
        { id: 11, transaction_type_id: 6, coa_id: 1, is_credit: 1 },
        { id: 12, transaction_type_id: 6, coa_id: 9, is_credit: 0 },
        { id: 13, transaction_type_id: 7, coa_id: 1, is_credit: 0 },
        { id: 14, transaction_type_id: 7, coa_id: 5, is_credit: 1 },
        { id: 15, transaction_type_id: 8, coa_id: 5, is_credit: 0 },
        { id: 17, transaction_type_id: 9, coa_id: 1, is_credit: 0 },
        { id: 18, transaction_type_id: 9, coa_id: 17, is_credit: 1 },
        { id: 19, transaction_type_id: 10, coa_id: 1, is_credit: 0 },
        { id: 20, transaction_type_id: 10, coa_id: 7, is_credit: 1 },
        { id: 21, transaction_type_id: 11, coa_id: 1, is_credit: 0 },
        { id: 22, transaction_type_id: 11, coa_id: 17, is_credit: 1 },
        { id: 23, transaction_type_id: 12, coa_id: 10, is_credit: 0 },
        { id: 24, transaction_type_id: 12, coa_id: 14, is_credit: 1 },
        { id: 25, transaction_type_id: 13, coa_id: 11, is_credit: 0 },
        { id: 26, transaction_type_id: 13, coa_id: 14, is_credit: 1 },
        { id: 27, transaction_type_id: 14, coa_id: 13, is_credit: 0 },
        { id: 28, transaction_type_id: 14, coa_id: 14, is_credit: 1 },
        { id: 29, transaction_type_id: 15, coa_id: 2, is_credit: 1 },
        { id: 30, transaction_type_id: 15, coa_id: 15, is_credit: 0 },
        { id: 31, transaction_type_id: 16, coa_id: 1, is_credit: 0 },
        { id: 32, transaction_type_id: 16, coa_id: 17, is_credit: 1 },
        { id: 33, transaction_type_id: 17, coa_id: 1, is_credit: 0 },
        { id: 34, transaction_type_id: 17, coa_id: 17, is_credit: 1 },
        { id: 35, transaction_type_id: 18, coa_id: 2, is_credit: 0 },
        { id: 36, transaction_type_id: 18, coa_id: 17, is_credit: 1 },
        { id: 37, transaction_type_id: 19, coa_id: 1, is_credit: 0 },
        { id: 38, transaction_type_id: 19, coa_id: 17, is_credit: 1 },
        { id: 39, transaction_type_id: 20, coa_id: 1, is_credit: 0 },
        { id: 40, transaction_type_id: 20, coa_id: 17, is_credit: 1 },
        { id: 41, transaction_type_id: 21, coa_id: 1, is_credit: 0 },
        { id: 42, transaction_type_id: 21, coa_id: 17, is_credit: 1 },
        { id: 43, transaction_type_id: 22, coa_id: 1, is_credit: 0 },
        { id: 44, transaction_type_id: 22, coa_id: 17, is_credit: 1 },
        { id: 45, transaction_type_id: 23, coa_id: 1, is_credit: 0 },
        { id: 46, transaction_type_id: 23, coa_id: 17, is_credit: 1 },
        { id: 47, transaction_type_id: 24, coa_id: 1, is_credit: 0 },
        { id: 48, transaction_type_id: 24, coa_id: 17, is_credit: 1 },
        { id: 49, transaction_type_id: 25, coa_id: 1, is_credit: 0 },
        { id: 50, transaction_type_id: 25, coa_id: 17, is_credit: 1 },
        { id: 51, transaction_type_id: 26, coa_id: 1, is_credit: 0 },
        { id: 52, transaction_type_id: 26, coa_id: 17, is_credit: 1 },
        { id: 53, transaction_type_id: 27, coa_id: 1, is_credit: 0 },
        { id: 54, transaction_type_id: 27, coa_id: 17, is_credit: 1 },
        { id: 55, transaction_type_id: 28, coa_id: 1, is_credit: 0 },
        { id: 56, transaction_type_id: 28, coa_id: 17, is_credit: 1 },
        { id: 57, transaction_type_id: 29, coa_id: 1, is_credit: 0 },
        { id: 58, transaction_type_id: 29, coa_id: 17, is_credit: 1 },
        { id: 59, transaction_type_id: 30, coa_id: 1, is_credit: 0 },
        { id: 60, transaction_type_id: 30, coa_id: 17, is_credit: 1 },
        { id: 61, transaction_type_id: 31, coa_id: 1, is_credit: 0 },
        { id: 62, transaction_type_id: 31, coa_id: 17, is_credit: 1 },
        { id: 63, transaction_type_id: 32, coa_id: 1, is_credit: 0 },
        { id: 64, transaction_type_id: 32, coa_id: 17, is_credit: 1 },
        { id: 65, transaction_type_id: 33, coa_id: 7, is_credit: 0 },
        { id: 66, transaction_type_id: 33, coa_id: 17, is_credit: 1 },
        { id: 67, transaction_type_id: 34, coa_id: 1, is_credit: 1 },
        { id: 68, transaction_type_id: 34, coa_id: 16, is_credit: 0 },
        { id: 69, transaction_type_id: 35, coa_id: 1, is_credit: 0 },
        { id: 70, transaction_type_id: 35, coa_id: 9, is_credit: 1 },
        { id: 71, transaction_type_id: 36, coa_id: 17, is_credit: 1 },
        { id: 72, transaction_type_id: 36, coa_id: 2, is_credit: 0 },
        { id: 73, transaction_type_id: 38, coa_id: 17, is_credit: 1 },
        { id: 74, transaction_type_id: 38, coa_id: 1, is_credit: 0 },
        { id: 75, transaction_type_id: 39, coa_id: 12, is_credit: 0 },
        { id: 76, transaction_type_id: 39, coa_id: 1, is_credit: 1 },
        { id: 77, transaction_type_id: 40, coa_id: 4, is_credit: 1 },
        { id: 78, transaction_type_id: 40, coa_id: 17, is_credit: 0 } 
    ]);
};
